USE [master]
GO

/****** Object:  Database [Progra 3 Bases de Datos]    Script Date: 31/10/2018 5:16:07 p. m. ******/
CREATE DATABASE [Progra 3 Bases de Datos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Progra 3 Bases de Datos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Progra 3 Bases de Datos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Progra 3 Bases de Datos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Progra 3 Bases de Datos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Progra 3 Bases de Datos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET ARITHABORT OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET RECOVERY FULL 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET  MULTI_USER 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Progra 3 Bases de Datos] SET  READ_WRITE 
GO


